import { useMemo, useState } from 'react';
import { RefreshCw, Info } from 'lucide-react';
import Button from '../../components/common/Button';
import { EmptyState } from '../../components/common/States';
import { MovieGrid } from '../../components/movies/MovieLists';
import { useAuth } from '../../context/AuthContext';
import { useAsync } from '../../hooks/useAsync';
import { recommendationService } from '../../services/recommendationService';

const PAGE = 12;

export default function ForYouPage() {
  const { user } = useAuth();
  const [refreshKey, setRefreshKey] = useState(0);
  const [genre, setGenre] = useState('All');
  const [sort, setSort] = useState('relevance');
  const [minRating, setMinRating] = useState(0);
  const [shown, setShown] = useState(PAGE);

  const { data, loading, error, reload } = useAsync(
    () => recommendationService.getRecommendations(user, { limit: 10, refresh: refreshKey > 0 }),
    [user?.id, refreshKey]
  );

  const genres = useMemo(() => ['All', ...new Set((data?.movies || []).flatMap((m) => m.genres || []))], [data]);
  
  const movies = useMemo(() => {
    let list = (data?.movies || []).filter((m) => {
      const matchGenre = genre === 'All' || (m.genres && m.genres.includes(genre));
      const matchRating = (m.vote_average || 0) >= minRating;
      return matchGenre && matchRating;
    });

    if (sort === 'rating') list = [...list].sort((a, b) => (b.vote_average || 0) - (a.vote_average || 0));
    if (sort === 'newest') list = [...list].sort((a, b) => String(b.release_date || '').localeCompare(String(a.release_date || '')));
    return list;
  }, [data, genre, sort, minRating]);

  const first = (user?.fullName || user?.username || '').split(' ')[0];

  return (
    <>
      <div className="pagehead">
        <h1>
          Picked for <em>{first || 'you'}</em>
          {data?.isFallback && <span className="pill" style={{ marginLeft: '8px', background: '#3b82f6', color: '#fff' }}>Popular Fallback</span>}
          {!data?.isFallback && data?.source === 'fastapi' && <span className="pill" style={{ marginLeft: '8px', background: '#10b981', color: '#fff' }}>SVD Model</span>}
        </h1>
        <p>
          {data?.isFallback
            ? 'Your user account has no model profile mapping yet. Displaying top popular movie recommendations from the backend.'
            : 'Personalized recommendations generated by the CineTale SVD Collaborative Filtering model.'}
        </p>
      </div>

      {data?.isFallback && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 16px', background: 'rgba(59, 130, 246, 0.1)', border: '1px solid rgba(59, 130, 246, 0.3)', borderRadius: '8px', marginBottom: '1.5rem', fontSize: '0.9rem', color: '#93c5fd' }}>
          <Info size={18} />
          <span>Note: Signed-in accounts (Supabase UUIDs) default to popular recommendations until mapped to model profiles.</span>
        </div>
      )}

      <div className="tools">
        <select aria-label="Sort" value={sort} onChange={(e) => setSort(e.target.value)}>
          <option value="relevance">Sort: Recommended order</option>
          <option value="rating">Highest rated</option>
          <option value="newest">Newest</option>
        </select>
        <select aria-label="Minimum rating" value={minRating} onChange={(e) => setMinRating(Number(e.target.value))}>
          <option value={0}>Any rating</option>
          <option value={3}>3+ ★</option>
          <option value={4}>4+ ★</option>
        </select>
        <Button variant="secondary" size="sm" onClick={() => { setShown(PAGE); setRefreshKey((k) => k + 1); }} disabled={loading}>
          <RefreshCw size={15} /> Refresh
        </Button>
      </div>

      {genres.length > 1 && (
        <div className="chipbar" role="group" aria-label="Genre filter">
          {genres.map((g) => (
            <button key={g} className={`gchip ${genre === g ? 'is-on' : ''}`} aria-pressed={genre === g} onClick={() => { setGenre(g); setShown(PAGE); }}>
              {g}
            </button>
          ))}
        </div>
      )}

      <MovieGrid
        movies={movies.slice(0, shown)}
        loading={loading}
        error={error}
        onRetry={reload}
        note={(m) => m.reason}
        empty={
          <EmptyState
            title="No recommendations available"
            message="Check back soon or explore movies in Discover."
            action={{ label: 'Discover movies', to: '/discover' }}
          />
        }
      />

      {!loading && !error && movies.length > shown && (
        <div style={{ textAlign: 'center', marginTop: '2rem' }}>
          <Button variant="secondary" onClick={() => setShown(shown + PAGE)}>Load more</Button>
        </div>
      )}
    </>
  );
}
